use_frameworks!

platform :ios, '9.0'

target 'DataBind_Example' do
  pod 'DataBind', :path => '../'

  # pod 'Observable-Swift'
  target 'DataBind_Tests' do
    inherit! :search_paths

    
  end
end
